apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: precis-ingress

spec:

  rules:

    - host: precis.local

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:

                name: precis-backend

                port:

                  number: 8000