FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install \
    --default-timeout=1000 \
    --retries=10 \
    --no-cache-dir \
    -r requirements.txt

COPY . .

CMD ["python", "ai_engine/main.py"]
