FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install \
    --default-timeout=1000 \
    --retries=10 \
    --no-cache-dir \
    -r requirements.txt

COPY . .

CMD ["uvicorn", "ai_engine.yolo.inference.services.ai_services.main:app", "--host", "0.0.0.0", "--port", "9000"]
