LOW_RISK_THRESHOLD = 2.0

MODERATE_RISK_THRESHOLD = 4.0

HIGH_RISK_THRESHOLD = 6.0

SEVERE_RISK_THRESHOLD = 8.0

CRITICAL_RISK_THRESHOLD = 9.0

MAX_RISK_SCORE = 10.0

TURBULENCE_WARNING_THRESHOLD = 4.5

TURBULENCE_CRITICAL_THRESHOLD = 7.5

BOTTLENECK_WARNING_THRESHOLD = 5.0

BOTTLENECK_CRITICAL_THRESHOLD = 8.0

OUTSTROKE_WARNING_PROBABILITY = 0.45

OUTSTROKE_CRITICAL_PROBABILITY = 0.75

RESONANCE_WARNING_PROBABILITY = 0.55

RESONANCE_CRITICAL_PROBABILITY = 0.82

DENSITY_WARNING_THRESHOLD = 5.5

DENSITY_CRITICAL_THRESHOLD = 8.5

SHOCKWAVE_TRIGGER_THRESHOLD = 7.0

EVACUATION_COMPLEXITY_WARNING = 5.0

EVACUATION_COMPLEXITY_CRITICAL = 8.0

MAX_ALLOWED_ZONE_PRESSURE = 9.5

LIVE_ALERT_COOLDOWN_SECONDS = 20

EMERGENCY_DISPATCH_TIMEOUT = 5

CRITICALITY_UPDATE_INTERVAL = 2